apiVersion: v1
kind: Service
metadata:
  namespace: hcwl
  name: hcwl-gateway
  labels:
    app: hcwl-gateway
spec:
  type: NodePort
  selector:
    app: hcwl-gateway
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
      nodePort: 8080