apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: hcwl
spec:
  capacity:
    storage: 5Gi # 根据实际大小调整
  accessModes:
    - ReadWriteMany # 允许多个读写访问
  nfs:
    path: /hcwl
    server: 192.168.0.100
  persistentVolumeReclaimPolicy: Retain # 可选，默认为 Delete，为 Retain
