apiVersion: v1
kind: Service
metadata:
  namespace: hcwl
  name: hcwl-rocketmq
  labels:
    app: hcwl-rocketmq
spec:
  type: NodePort
  selector:
    app: hcwl-rocketmq
  ports:
    - port: 9876
      protocol: TCP
      name: http9876
      nodePort: 9876
    - port: 8080
      protocol: TCP
      name: http8081
      nodePort: 8081
    - port: 10909
      protocol: TCP
      name: http10909
      nodePort: 10909
    - port: 10911
      protocol: TCP
      name: http10911
      nodePort: 10911
    - port: 10912
      protocol: TCP
      name: http10912
      nodePort: 10912
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hcwl
  name: hcwl-rocketmq
  labels:
    app: hcwl-rocketmq
spec:
  selector:
    matchLabels:
      app: hcwl-rocketmq
  template:
    metadata:
      labels:
        app: hcwl-rocketmq
    spec:
      containers:
        - name: hcwl-rocketmq
          image: xuchengen/rocketmq:5.0.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
          ports:
            - containerPort: 9876
              name: http9876
              protocol: TCP
              hostPort: 9876
            - containerPort: 8080
              name: http8080
              protocol: TCP
              hostPort: 8080
            - containerPort: 10909
              name: http10909
              protocol: TCP
              hostPort: 10909
            - containerPort: 10909
              name: http10911
              protocol: TCP
              hostPort: 10911
            - containerPort: 10912
              name: http10912
              protocol: TCP
              hostPort: 10912
