apiVersion: v1
kind: ConfigMap
metadata:
  name: hcwl-nacos
  namespace: hcwl
data:
  mysql.host: "192.168.0.150"
  mysql.db.name: "nacos"
  mysql.port: "3306"
  mysql.user: "nacos"
  mysql.password: "Hongyang@nacos"
---
apiVersion: v1
kind: Service
metadata:
  name: hcwl-nacos
  namespace: hcwl
  labels:
    app: hcwl-nacos
spec:
  type: NodePort
  ports:
    - port: 8848
      name: server
      targetPort: 8848
      nodePort: 8848
    - port: 9848
      name: client-rpc
      targetPort: 9848
      nodePort: 9869
    - port: 9849
      name: raft-rpc
      targetPort: 9849
      nodePort: 9849
  selector:
    app: hcwl-nacos
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hcwl-nacos
  namespace: hcwl
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: hcwl-nacos
    spec:
      containers:
        - name: hcwl-nacos
          image: registry.cn-shenzhen.aliyuncs.com/hcwl-public/nacos:v2.2.0-slim
          ports:
            - containerPort: 8848
              name: client
            - containerPort: 9848
              name: client-rpc
            - containerPort: 9849
              name: raft-rpc
          env:
            - name: SPRING_DATASOURCE_PLATFORM
              value: "mysql"
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: hcwl-nacos
                  key: mysql.host
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: hcwl-nacos
                  key: mysql.db.name
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: hcwl-nacos
                  key: mysql.port
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: hcwl-nacos
                  key: mysql.user
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: hcwl-nacos
                  key: mysql.password
            - name: MODE
              value: "standalone"
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
  selector:
    matchLabels:
      app: hcwl-nacos