apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hcwl
  name: hcwl-module-job
  labels:
    app: hcwl-module-job
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hcwl-module-job
  template:
    metadata:
      labels:
        app: hcwl-module-job
    spec:
      imagePullSecrets:
        - name: aliyun-registry-secret
      restartPolicy: Always
      containers:
        - name: hcwl-module-job
          imagePullPolicy: Always
          image: swr.cn-north-4.myhuaweicloud.com/zk-project/hcwl-module-job:latest
          ports:
            - containerPort: 9998
              name: http9998
              protocol: TCP
              hostPort: 9998
          resources:
            requests:
              memory: 256Mi
            limits:
              memory: 1Gi