apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hcwl
  name: hcwl-auth
  labels:
    app: hcwl-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hcwl-auth
  template:
    metadata:
      labels:
        app: hcwl-auth
    spec:
      imagePullSecrets:
        - name: aliyun-registry-secret
      restartPolicy: Always
      containers:
        - name: hcwl-auth
          imagePullPolicy: Always
          image: registry-vpc.cn-shenzhen.aliyuncs.com/k8s-hcwl-cloud/hcwl-auth:latest
          resources:
            requests:
              memory: 128Mi
            limits:
              memory: 1Gi
          ports:
            - containerPort: 9200
              name: http9200
              protocol: TCP
              hostPort: 9200
          volumeMounts:
            - mountPath: /hcwl
              name: nfs-volume
              readOnly: false
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs-pvc
